# Generated by Django 5.0.2 on 2024-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_link',
        ),
        migrations.AlterField(
            model_name='investmentpackage',
            name='currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
    ]
