# Generated by Django 5.0.2 on 2024-02-26 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_remove_referral_referral_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.withdrawalrequest'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('earning', 'Earning'), ('referral', 'Referral Commission')], max_length=20),
        ),
    ]
