# Generated by Django 5.0.2 on 2024-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_remove_profile_btc_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='to_address',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
