# Generated by Django 5.0.2 on 2024-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_remove_customuser_token_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
