# Generated by Django 5.0.2 on 2024-03-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_alter_customuser_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usdt_trc20_wallet_address',
            new_name='usdt_erc20_wallet_address',
        ),
    ]
